import {createApi, progress} from './api.js';
const api=createApi(), app=document.querySelector('#app'), notice=document.querySelector('#notice');
const areas={VOCABULARY:'어휘 이해',BACKGROUND_KNOWLEDGE:'배경지식',COMPREHENSION:'개념 이해'};
let topics=[], session=null, position=0, selectedTopic='', user='1', busy=false, lastProfile=null, recommendationKey='';
const escape=s=>String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saved=()=>{try{return localStorage.getItem('bookmatch-session');}catch{return null;}};
const remember=value=>{try{value ? localStorage.setItem('bookmatch-session',value) : localStorage.removeItem('bookmatch-session');}catch{/* Storage is optional. */}};
function stage(n){document.body.dataset.stage=String(n);document.querySelectorAll('#steps li').forEach((e,i)=>{e.classList.toggle('active',i===n);if(i===n)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});}
function error(e){notice.textContent=e.message+(e.traceId ? ` (문의 번호: ${e.traceId})` : '');notice.hidden=false;}
async function run(fn){if(busy)return;busy=true;notice.hidden=true;app.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);try{await fn();}catch(e){error(e);}finally{busy=false;app.querySelectorAll('button,input,select').forEach(e=>e.disabled=false);}}
function focus(){app.querySelector('h1,legend')?.setAttribute('tabindex','-1');app.querySelector('h1,legend')?.focus();}
function choose(){stage(0);app.innerHTML=`<h1>어떤 분야를 읽고 싶나요?</h1><p class="muted">분야를 고르면 간단한 자기평가를 시작합니다.</p><form id="start"><details class="account-settings"><summary>체험 계정 설정</summary><label for="user">데모 사용자 번호</label><input id="user" type="number" min="1" step="1" required value="${escape(user)}"><small>팀에서 준비한 사용자 번호를 사용해 주세요.</small></details><label for="topic">학습 분야</label><select id="topic" required><option value="">분야를 선택해 주세요</option>${topics.filter(t=>t.parentId!==null).map(t=>`<option value="${t.id}" ${String(t.id)===selectedTopic?'selected':''}>${escape(t.name)}</option>`).join('')}</select><div class="actions"><button type="submit">자기평가 시작</button>${saved()?'<button type="button" id="resume" class="secondary">이전 진단 이어하기</button>':''}</div></form><p class="note">알고 있는지를 스스로 판단하는 진단입니다. 정답을 맞히는 시험이 아니니 편하게 답해 주세요.</p>`;
app.querySelector('#start').onsubmit=e=>{e.preventDefault();user=app.querySelector('#user').value;selectedTopic=app.querySelector('#topic').value;run(async()=>{session=await api.create(user,selectedTopic);remember(String(session.id));position=0;question();});};
app.querySelector('#resume')?.addEventListener('click',()=>run(restore));}
async function restore(){session=await api.session(saved());user=String(session.userId);selectedTopic=String(session.topicId);position=Math.max(0,session.questions.findIndex(q=>q.knowsConcept===null));if(session.status==='COMPLETED'){const done=await api.complete(session.id);result(done.profile);}else question();}
function question(){stage(1);const q=session.questions[position], p=progress(session.questions);if(!q)throw new Error('진단 문항이 없습니다. 팀에 문의해 주세요.');
const locked=session.status==='PROCESSING';
app.innerHTML=`<h1>익숙한 개념을 알려주세요</h1><p class="muted">${position+1} / ${p.total} 문항 · ${p.answered}개 저장됨</p><progress value="${p.answered}" max="${p.total}" aria-label="저장한 답변 수"></progress><form id="answer"><small>${escape(areas[q.measurementArea] || q.measurementArea)}</small><fieldset><legend>${escape(q.prompt)}</legend>${[[true,'알고 있어요'],[false,'아직 익숙하지 않아요']].map(([v,t])=>`<label class="choice"><input type="radio" name="knows" value="${v}" required ${q.knowsConcept===v?'checked':''}>${t}</label>`).join('')}</fieldset><div class="actions">${position>0?'<button type="button" id="previous" class="secondary">이전 문항</button>':''}<button type="submit">${position===p.total-1?'답변 저장':'저장하고 다음'}</button></div></form>${p.complete?'<div class="actions"><button id="complete">프로필 확인하기</button></div>':''}<div class="actions"><button id="reload" class="secondary">저장 상태 다시 확인</button><button id="home" class="secondary">분야 선택으로</button></div>${locked?'<p class="note">결과를 계산 중입니다. 잠시 후 저장 상태를 다시 확인해 주세요.</p>':''}`;
app.querySelector('#answer').onsubmit=e=>{e.preventDefault();const choice=new FormData(e.target).get('knows');run(async()=>{const answer=await api.answer(session.id,q.id,choice==='true');session.questions[position]={...q,...answer};if(position<p.total-1)position++;question();focus();});};
app.querySelector('#previous')?.addEventListener('click',()=>{position--;question();focus();});
app.querySelector('#complete')?.addEventListener('click',()=>run(async()=>{const done=await api.complete(session.id);session.status=done.status;result(done.profile);focus();}));
app.querySelector('#reload').onclick=()=>run(restore);
app.querySelector('#home').onclick=choose;
if(locked)app.querySelector('#answer').hidden=true;
}
function percent(value){return Number.isFinite(Number(value))?`${Math.round(Number(value)*100)}%`:'평가 근거 없음';}
function result(profile){lastProfile=profile;recommendationKey=crypto.randomUUID();stage(2);app.innerHTML=`<h1>나의 읽기 준비도</h1><p class="muted">저장한 답변을 바탕으로 정리한 프로필입니다.</p>${[['vocabulary','어휘 이해'],['backgroundKnowledge','배경지식'],['comprehension','개념 이해']].map(([k,title])=>{const value=Number(profile[k]);if(!Number.isFinite(value)||value<0||value>1)throw new Error('프로필 점수를 확인할 수 없습니다.');return `<div class="result"><div><span>${title}</span><strong>${Math.round(value*100)}%</strong></div><progress value="${value}" max="1" aria-label="${title}"></progress></div>`;}).join('')}<p class="note">자기평가 기반의 참고 정보입니다.${String(profile.calculationVersion).startsWith('stub')?' 현재는 데모 계산 결과이며 실제 ML 평가가 아닙니다.':''}</p><small>계산 버전: ${escape(profile.calculationVersion)}<br>진단 번호: ${escape(profile.sessionId)}</small><div class="actions"><button id="recommend">추천 도서 확인하기</button><button id="restart" class="secondary">다른 분야 살펴보기</button></div>`;
app.querySelector('#recommend').onclick=()=>run(async()=>{const recommendation=await api.recommend(user,selectedTopic,recommendationKey);recommendations(recommendation);focus();});
app.querySelector('#restart').onclick=()=>{remember(null);lastProfile=null;choose();};}
function recommendations(data){if(!Array.isArray(data?.items))throw new Error('추천 결과를 확인할 수 없습니다.');stage(2);const cards=data.items.map(item=>`<article class="recommendation-card"><div class="recommendation-head"><span class="rank-badge">${escape(item.rank)}순위</span><div><h2>${escape(item.title)}</h2><p>${escape(item.author || '저자 정보 없음')}</p></div></div><div class="metric-grid"><div class="metric"><span>선행지식 준비도</span><strong>${percent(item.prerequisiteReadiness)}</strong><small>${escape(item.prerequisiteAssessedCount ?? 0)} / ${escape(item.prerequisiteTotalCount ?? 0)}개 평가</small></div><div class="metric"><span>배울 여지</span><strong>${percent(item.directLearningOpportunity)}</strong><small>${escape(item.directAssessedCount ?? 0)} / ${escape(item.directTotalCount ?? 0)}개 평가</small></div></div>${item.coveredConcepts?.length?`<p class="concepts"><b>다루는 개념</b> ${item.coveredConcepts.map(escape).join(' · ')}</p>`:''}${item.reasons?.length?`<ul class="reason-list">${item.reasons.map(reason=>`<li>${escape(reason)}</li>`).join('')}</ul>`:''}</article>`).join('');
const shortage=Number(data.diagnostics?.personalizedCandidateShortage||0);app.innerHTML=`<h1>지금 읽기 좋은 책</h1><p class="muted">나의 개념 준비도와 책의 선행지식을 비교한 결과입니다.</p>${cards||'<div class="empty-result"><strong>현재 개인화할 수 있는 책이 없습니다.</strong><p>도서의 개념 근거가 더 준비되면 추천 결과를 보여드릴 수 있어요.</p></div>'}${shortage>0?`<p class="note">요청한 수보다 개인화 가능한 책이 ${escape(shortage)}권 부족해 확인 가능한 결과만 표시했습니다.</p>`:''}<small>추천 모델: ${escape(data.modelVersion)} · 추천 번호: ${escape(data.id)}</small><div class="actions"><button id="profile-back" class="secondary">프로필로 돌아가기</button><button id="restart">처음부터 다시 하기</button></div>`;
app.querySelector('#profile-back').onclick=()=>result(lastProfile);app.querySelector('#restart').onclick=()=>{remember(null);lastProfile=null;choose();};}
async function load(){app.innerHTML='<h1>학습 분야를 불러오는 중…</h1>';try{topics=await api.topics();choose();}catch(e){app.innerHTML='<h1>연결을 확인해 주세요</h1><p>백엔드가 실행되면 학습 분야를 불러올 수 있어요.</p><button id="retry">다시 연결</button>';error(e);app.querySelector('#retry').onclick=()=>{notice.hidden=true;load();};}}
load();
